backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "img/uploads" # Media files will be stored in the repo under images/uploads
collections:
  - name: "testimonies" # Used in routes, e.g., /admin/collections/blog
    label: "testimonies" # Used in the UI
    folder: "testimonials" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout",  widget: "hidden", name: "layout", default: "testimonies"}
      - {label: "tags", widget: "hidden", name: "tags",  default: testimonies}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown", hint: 'Main content goes here.'}